---
- hosts: "{{ servers }}"
  become: yes
  become_method: sudo
  tasks:

## To create a hashed password for the user like you see below run the following at the command line (requires python3-passlib package):
## python3 -c "from passlib.hash import sha512_crypt; import getpass; print(sha512_crypt.hash(getpass.getpass()))"

    - name: "Create ansible user"
      ansible.builtin.user:
        name: ansible
        state: present
        createhome: yes
        shell: /bin/bash
        ## Uncomment the line below and replace the hash with the one created with the python on-liner above to assign a password for the user
        # password: "$6$rounds=656000$w8PsKlU43B8FO3nV$8GAz00hibxYOLbrgH60e/lDX4DdZE.JuTMSbvdPp0VnjnEY8o5eiLWENYUX3N19XJOT/Y7Z9F02s28m85GUE61"

    - name: Grant ansible user sudo rights without password
      ansible.builtin.lineinfile:
        dest: /etc/sudoers.d/ansible
        create: yes
        mode: 0440
        line: 'ansible ALL=(ALL) NOPASSWD: ALL'

    - name: Add management server ansible key to ansible user on remote systems authorized_key file 
      ansible.posix.authorized_key: 
        user=ansible 
        key="{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
