## The collections in here will install by default into ~/.ansible/collections/ansible_collections
collections:
  - name: ansible.posix
    version: 1.5.4
  - name: community.general
    version: 7.3.0