---
## This is a fancy script to run a specific role or multiple comma seperated roles against a specific server

## Usage example: ansible-playbook run_role.yml -i servers.yml --extra-vars="servers='ubuntu_server_1' role=fix_updates"

- name: "Run role(s) {{ role | default (roles, True) }} against {{ servers }}"
  hosts: "{{ servers }}"
  gather_facts: "{{ gf | default(omit, True) }}"
  become: "{{ elevate | default(omit, True) }}"
  tasks:
    - include_role:
        name: "{{ role_name }}"
      loop: "{{ role | default (roles, True) | split(',') | list }}"
      loop_control:
        loop_var: role_name